#!/bin/zsh
PAUSE=20
if [[ -z "$*" ]]; then
    echo -n "provide the time." >&2
    exit 1
else
    WHEN="$*"
fi
date -d $WHEN >/dev/null || exit
DEST_TIME=$(date -d $WHEN +%s)


zmodload zsh/mathfunc
DIFFSEC=$(($(date -d $WHEN +%s) - $(date +%s)))
HOURS=$((int($DIFFSEC / 60. / 60. )))
MINUTES=$((int(($DIFFSEC - $HOURS * 60 * 60) / 60.)))
printf "Alarm will sound at %s [in %d:%02d from now]\n" "$(date -d $WHEN)" $HOURS $MINUTES

rtcwake -t $DEST_TIME -m no  # /usr/bin/chmod ugo+r /dev/rtc0 
                             # for this to work

hook() { 
    # ~/r/alrm/postwakeup.sh
    exit
}
trap hook SIGINT

while [[ $(date +%s) -lt $DEST_TIME ]]; do
    sleep 1m
done

while true; do
    mpv --shuffle --no-video ~/Music/alarmtone
    espeak "$(date +%H:%M)"
    echo Repeating in $PAUSE minutes; sleep ${PAUSE}m
done

