#!/bin/zsh
PAUSE=20
if [[ -z "$*" ]]; then
    echo -n "provide the time." >&2
    exit 1
else
    WHEN="$*"
fi
date -d $WHEN >/dev/null || exit
DEST_TIME=$(date -d $WHEN +%s)

echo "Alarm will sound: $(date -d $WHEN) [in $((($(date -d $WHEN +%s) - $(date +%s)) / 60.0 / 60.0)) hours]"

rtcwake -t $DEST_TIME -m no

hook() { 
    ${0:a:h}/postwakeup.sh
    exit
}
trap hook SIGINT

while [[ $(date +%s) -lt $DEST_TIME ]]; do
    sleep 1m
done

while true; do
    mpv --shuffle ~/Music/alarmtone
    echo Repeating in $PAUSE minutes; sleep ${PAUSE}m
done

